# Generated by Django 2.1.4 on 2019-08-07 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_user_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='p_buy_user', to='Index.User'),
            preserve_default=False,
        ),
    ]
