# Generated by Django 2.1.4 on 2019-08-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_product_buy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buy_user',
        ),
        migrations.AddField(
            model_name='product',
            name='buy_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
