# Generated by Django 2.1.4 on 2019-08-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0005_auto_20190807_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_success_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
